### ISSUE TITLE
custom wake word problem at startup at rpi3b+

### ISSUE THREAD

**Issue by michauPe** [MycroftAI/mycroft-precise#134] opened 2020-03-04 09:25 UTC
I am facing issue with custom wake word setup of picroft at startup - after mycroft  boot is complete, my wake word is constantly being invoked by any sound. It is very often ( almost every second reboot). If this happen I usually need to run `mycroft-start restart all` and then everthing is ok. How to deal with it ? Please help. Thx.

**Comment by krisgesling** [comment] 2020-03-09 11:26
Hi michau, it sounds like Precise may be failing to load and it is instead falling back to PocketSphinx. 

When the problem is happening, can you ask Mycroft:
> Hey Mycroft, what is the Listener?

Is this on a Picroft image? If so can you reply with the Picroft image filename that you used so we can see which date it is?

**Comment by michauPe** [comment] 2020-03-10 11:14
Hi, it sounds like you wrote. The good thing is that since last 10 reboots it haven't happened, so I cant reproduce this bug and check listener. Now i am ruuning ver 20.2.1 and the image file of picroft was from 2020.01.10.

Btw - is something what i can do to prevent this potential issue in future ?

**Comment by krisgesling** [comment] 2020-03-10 12:03
This is a total guess, but I'd assume that Precise was corrupted in some way and that it's now downloaded a fresh copy which is now working as expected. It comes pre-installed on the image so this shouldn't happen, but it's possible. 

Another possibility is if something was causing the mic-level to get jacked right up, perhaps the wake word model might have interpreted the excessive noise as an activation? I think the Precise issue is more likely though.

We've got it on the backlog to look at a more robust delivery mechanism for these resources which would minimise the chance of this happening.

If we can't reproduce at the moment I'll close this issue, but please reopen if it returns and we can dig further.

**Closed as completed by krisgesling** 2020-03-10 12:03 UTC
